name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Cloning the repository.
        uses: actions/checkout@v4

      - name: ğŸ”§ Installing dependencies.
        run: pip install -r requirements.txt

      - name: ğŸ“Š Generating the chart and analysis.
        run: python analysis.py 
      
      - name: ğŸ“Š Generating the chart and analysis.
        run: python graf.py #This script will create `crypto_graph.html` and `analysis.txt`

      - name: ğŸ“‚ Preparing files for publication
        run: |
          mkdir -p public
          cp templates/index.html public/index.html
          cp static/styles.css public/
          cp static/script.js public/
          cp crypto_graph.html public/
          cp analysis.txt public/

      - name: ğŸš€ Uploading the artifact for GitHub Pages.
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

      - name: ğŸŒ Publishing on GitHub Pages.
        uses: actions/deploy-pages@v2
