name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  push:
    branches:
      - master  # Run on push to the master branch
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: ğŸ“¥ Cloning the repository
        uses: actions/checkout@v4  # Checkout the repository

      - name: ğŸ”§ Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: ğŸ“Š Running analysis and generating chart
        run: |
          python analysis.py  # Run analysis.py to generate data
          python graf.py  # Generate the chart

      - name: ğŸ“‚ Preparing files for publication
        run: |
          mkdir -p public
          cp templates/index.html public/index.html
          cp static/styles.css public/
          cp static/script.js public/
          cp static/icon/favicon.ico public/
          cp crypto_chart.html public/  # Make sure the generated chart is copied
          cp analysis.txt public/  # Copy the analysis file

      - name: ğŸš€ Uploading the artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: ğŸŒ Publishing on GitHub Pages
        uses: actions/deploy-pages@v3
