name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Cloning the repository
        uses: actions/checkout@v3

      - name: ğŸ”§ Setting up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Installing dependencies
        run: |
          pip install -r requirements.txt

      - name: ğŸ“Š Running analysis and generating chart
        run: |
          python analysis.py
          python graf.py

      - name: ğŸ§ Check file generation
        run: |
          ls -l
          ls -l crypto_chart.html
          ls -l analysis.txt

      - name: ğŸ“‚ Preparing files for publication
        run: |
          mkdir -p public
          cp templates/index.html public/index.html
          cp static/styles.css public/
          cp static/script.js public/
          cp static/icon/favicon.ico public/
          cp crypto_chart.html public/
          cp analysis.txt public/

      - name: ğŸš€ Uploading the artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

      - name: ğŸŒ Publishing to GitHub Pages
        uses: actions/deploy-pages@v2
